# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    type: closed
    branches: 
      - master 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Update Twilio Studio Flow
      if: github.event.pull_request.merged = true
      env:
        TWILIO_ACCOUNT_SID : ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN : ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FLOW_SID : ${{ secrets.TWILIO_FLOW_SID }}
      run: |
        curl -X POST https://studio.twilio.com/v2/Flows/${TWILIO_FLOW_SID} --data-urlencode "CommitMessage=Prod release v2" --data-urlencode "Definition@flow/flow.json" --data-urlencode "Status=published" -u ${TWILIO_ACCOUNT_SID}:${TWILIO_AUTH_TOKEN}
